baseURL = "https://fjchen.top/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# enableEmoji = true
# 文章摘要长度
# summaryLength = 0
# 网站标题
title = "fjchen"
publishDir = 'docs'
theme = "LoveIt"

[author]
  name = "fjchen"
  # email = ""
  link = "fjchen.top"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# 配置的说明文档：
# https://hugoloveit.com/zh-cn/theme-documentation-basics/#site-configuration
# https://www.angularjswiki.com/fontawesome/
[params]
  # 主题的版本
  version = "0.2.X"
  # 网站关键词
  keywords = ["Development", "开发", "Programming", "Code", "编程", "Life", "生活", "Reading", "阅读"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "light"

  # 搜索配置
  [params.search]
    enable = false

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "normal"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # 页面头部导航栏标题配置
    [params.header.title]
  #     # LOGO 的 URL
  #     logo = ""
      # 标题名称
      name = 'fjchen'
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = '<i class="far fa-kiss-wink-heart"></i>'
  #     # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      # post = ""
      # 是否为标题显示打字机动画
      typeit = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    # 自定义内容 (支持 HTML 格式)
    custom = '<strong>All those moments will be lost in time, like tears in rain.</strong>'
    # 是否显示 Hugo 和主题信息
    hugo = false
    # 是否显示版权信息
    copyright = true
    # 是否显示作者
    author = true
    # 网站创立年份
    since = 2022
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    seriesNavigation = true

  # Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 40
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 20

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 40
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 20

  # 主页配置
  [params.home]
    # RSS 文章数目
    rss = 20
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.jpg"
      # LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = "fjchen的自留地"
      # 主页显示的网站副标题
      subtitle = ''
      # 是否为副标题显示打字机动画
      typeit = false
      # 是否显示社交账号
      social = true
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 5

  # 社交信息设置
  [params.social]
    GitHub = "fjchen7"
    Twitter = "fjchen7"
    RSS = true

  # 文章页面配置
  [params.page]
    # 是否使用 Twitter Emoji
    twemoji = true
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    # linkToMarkdown = true
    # 是否在 RSS 中显示全文内容
    rssFullText = true
    # 页面样式 ("normal", "wide")
    pageStyle = "normal"
    # 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = false
    # 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 10
    # KaTeX 数学公式
    [params.page.math]
      enable = true
    # Mapbox GL JS 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Weibo = true
      Reddit = true
    # 评论系统设置
    [params.page.comment]
      enable = true
      # Utterances 评论系统设置
      # Utterances 的评论记录在 GitHub Issues 里，需要在仓库安装 utterances：https://github.com/apps/utterances
      [params.page.comment.utterances]
        enable = true
        # owner/repo
        repo = "fjchen7/fjchen7.github.io"
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
    # 第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"
    # LoveIt 更改 | 0.2.10 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      # images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = "fjchen"
        # logoUrl = ""

  # 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""

  # 网站分析配置
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    # pre = "<i class='fas fa-list-ul'></i>"
    pre = "<i class='fas fa-ellipsis-v'></i>"
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = "<i class='fas fa-tags'></i>"
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "About"
    pre = "<i class='fas fa-glasses'></i>"
    post = ""
    name = "关于我"
    url = "/about"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
